name: spiral
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - mlflow
    - tensorflow
    - pyyaml
    - pandas
    - seaborn
    - tables
    - sklearn
    - skrebate
    - sampen
    - xlrd
    - hfda
    - pyentrp
    - google-cloud-storage
    - pytz  