version: "3.7"

services:

  mlflow:                                             # create a MLFlow container
    build: './mlflow'                        # construct the container along the Dockerfile in this folder
    container_name: mlflow_container
    ports:
        - "5001:5000"                               # expose port
    command: 'mlflow server --backend-store-uri ./mlflow --host 0.0.0.0 --port 5000'
    