version: "3.7"

services:
  spiral:
    build: .
    image: deep-learning-workstation:5000/spiral
    networks:
      - public
    command: jupyter notebook --allow-root --ip=0.0.0.0
    ports:
      - "8888:8888"
      - "8887:8080"
    volumes:
      - /data:/data
      - ../..:/home/jovyan/spiral
      - /data/resources/cloud/gcp/keys:/tmp/keys
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
networks:
  public:
    external: true
    name: public