version: "3.7"

services:
  spiral:
    build: .
    image: deep-learning-workstation:5000/spiral-jupyter
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/keys/eastonlab-b37c04a8f1a5.json"
      MLFLOW_TRACKING_URI: "http://192.168.1.12:5001"
    command: jupyter notebook --allow-root --ip=0.0.0.0
    ports:
      - "8888:8888"
      - "8887:8080"
    volumes:
      - /data:/data
      - ../..:/home/jovyan/spiral
      - /data/resources/cloud/gcp/keys:/tmp/keys
    networks:
      - public
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
networks:
  public:
    external: true
    name: public