name: elekin
channels:
  - anaconda
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - h5py
  - hdf5
  - numpy
  - pandas
  - pip
  - python
  - setuptools
  - tensorboard
  - tensorflow
  - pip:
    - hfda
    - joblib
    - sampen
    - scikit-learn
    - sklearn
    - swifter